// ui-source/src/pages/Vehicles.svelte
<script lang="ts">
  import {
    Badge,
    Button,
    ButtonGroup,
    Card,
    CardBody,
    CardFooter,
    CardHeader,
    El,
    Fieldset,
    FormInput,
    Input,
  } from 'yesvelte';
</script>

<section class="w-full h-full relative">
  <El tag="h1" class=" text-2vw w-full">Vehicles</El>
  <El class="w-full flex justify-center items-center">
    <FormInput class="w-100">
      <Button color="primary" slot="end">Search</Button>
    </FormInput>
  </El>
  <Fieldset class="w-full h-85% absolute flex-center">
    <Card class="w-full">
      <CardHeader class="text-center w-full">Vehicle Information</CardHeader>
      <CardBody>
        <El row>
          <FormInput readonly col="6" label="Vehicle Owner:" />
          <FormInput readonly col="6" label="Vehicle Name:" />
          <FormInput readonly col="12" label="Vehicle Plate:" />
          <FormInput readonly col="12" label="Vehicle Category:" />
          <FormInput readonly col="12" label="Vehicle Color:" />
          <Badge color="youtube" col="2">Warrant Found</Badge>
        </El>
      </CardBody>
      <CardFooter class="w-full">
        <ButtonGroup class="w-full ">
          <Button color="youtube">Add Warrant</Button>
          <Button>Remove Warrant</Button>
          <Button color="primary">Locate Vehicle</Button>
        </ButtonGroup>
      </CardFooter>
    </Card>
  </Fieldset>
</section>

// ui-source/src/pages/Vehicles.tsx
import { Button } from '@/components/ui/button';
import {
  TextField,
  TextFieldInput,
  TextFieldLabel,
} from '@/components/ui/textfield';
import { JSX } from 'solid-js';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
const Texto = (props: {
  title: number | boolean | Node | JSX.ArrayElement | (string & {});
  place: string;
}) => {
  return (
    <>
      <TextField>
        <TextFieldLabel class='text-background'>{props.title}</TextFieldLabel>
        <TextFieldInput type='text' placeholder={props.place} />
      </TextField>
    </>
  );
};

const Vehicles = () => {
  return (
    <>
      <div class='p-3 h-full w-full'>
        <p class='text-background text-4xl'>Vehicle Info</p>
        <div class='w-full flex justify-center items-center mt-3'>
          <TextField class='w-[30vw] bg-foreground text-background '>
            <TextFieldInput
              class='bg-foreground text-center'
              type='text'
              placeholder='Plate of the vehicle'
            />
          </TextField>
          <Button>Search</Button>
        </div>
        <div
          id='vehicleInformation'
          class='mt-3 grid grid-cols-1 w-full  gap-10'
        >
          <Card class='bg-foreground'>
            <CardHeader>
              <CardTitle class='text-background'>Vehicle Information</CardTitle>
              <CardDescription class='text-background'>
                Information about vehicle:Plate
              </CardDescription>
            </CardHeader>
            <CardContent class='grid grid-cols-1 gap-5'>
              <Texto title='Vehicle Owner' place='JERICOFX' />
              <Texto title='Vehicle Name' place='PRIMO' />
              <Texto title='Vehicle Garage' place='In Garage' />
              <Badge variant='destructive'>Warrant Found</Badge>
            </CardContent>
            <CardFooter class='grid grid-cols-3 gap-3'>
              <Button variant='destructive'>Check Warrant</Button>
              <Button>Create Warrant</Button>
              <Button variant='ghost' class='text-background'>
                Something Else
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </>
  );
};

export default Vehicles;
